name: dart_postgres_example
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://innovationgroup.tech
# author: Kenneth Reilly <kennneth@innovationgroup.tech>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  shelf: ^0.7.2
  dotenv: ^1.0.0
  postgres: ^1.0.2

dev_dependencies:
  pedantic: ^1.0.0
